PomodoroApplicationFinal/Controllers/HomeController.cs
using Pomodoro.Data;
using Pomodoro.Data.Contexts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PomodoroApplicationFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var db = new ApplicationDbContext();

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PomodoroApplicationFinal/Controllers/RewardController.cs
using Microsoft.AspNet.Identity;
using Pomodoro.Contracts;
using Pomodoro.Models.Reward;
using Pomodoro.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PomodoroApplicationFinal.Controllers
{
    [Authorize]
    public class RewardController : Controller
    {
        private readonly IRewardService _rewardService;

        public RewardController(IRewardService rewardService)
        {
            _rewardService = rewardService;
        }

        // GET: Reward
        public ActionResult Index()
        {
            //var model = new RewardListItem[0];
            //return View(model);

            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RewardService(userId);
            var model = service.GetReward();

            return View(model);
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RewardCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateRewardService();

            if (service.CreateReward(model))
            {
                TempData["SaveResult"] = "Your Reward was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Note could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateRewardService();
            var model = svc.GetRewardById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateRewardService();
            var detail = service.GetRewardById(id);
            var model =
                new RewardEdit
                {
                    RewardId = detail.RewardId,
                    RewardName = detail.RewardName,
                    Description = detail.Description,
                    PointCost = detail.PointCost
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RewardEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.RewardId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateRewardService();

            if (service.UpdateReward(model))
            {
                TempData["SaveResult"] = "Your note was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your note could not be updated.");
            return View(model);
        }

        
        public ActionResult Delete(int id)
        {

            var svc = CreateRewardService();
            var model = svc.GetRewardById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateRewardService();

            service.DeleteReward(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }

        private RewardService CreateRewardService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RewardService(userId);
            return service;
        }
    }
}

PomodoroApplicationFinal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PomodoroApplicationFinal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PomodoroApplicationFinal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">

<div class="jumbotron">
    <h1>Pomodoro Timer</h1>
    <br />
    <h3 class="text-center">Welcome to my Eleven Fifty Red Badge Application</h3>
    <br />
    <h4 class="text-center">The Pomodoro Technique is a time management method for students, perfectionists, and procrastinators of all kinds.</h4>
    <br />
    <h4 class="text-center">Work in focused 25-minute intervals.  Then take a 5-minute break</h4>
    <h4 class="text-center">Rinse and Repeat!</h4>
    <h4 class="text-center">See how many points you can get!</h4>
</div>

@*<div class="container">
        <div class="row">
            <div class="col-md-2">
                <div id="work-timer" class="timer">
                    <p id="w_minutes">0</p><p class="semicolon">:</p><p id="w_seconds">5</p>
                </div>
            </div>
            <div class="col-md-2">
                <div id="break-timer" class="timer">
                    <p id="b_minutes">0</p><p class="semicolon">:</p><p id="b_seconds">1</p>
                </div>
            </div>
        </div>
    </div>

        <div>
            <div class="row">
                <div class="col-md-2">
                    <p id="w_minutes">0</p><p class="semicolon">:</p><p id="w_seconds">5</p>

                </div>
                <div class="col-md-2">
                    One of three columns
                </div>

            </div>
        </div>*@


<div id="container">
    <p id="work" class="label">Work:</p>
    <p id="break" class="label">Break:</p>
    <p id="cycles" class="label">Points:</p>

    <div id="work-timer" class="timer">
        <p id="w_minutes">0</p>
        <p class="semicolon">:</p>
        <p id="w_seconds">10</p>
    </div>
    <div id="break-timer" class="timer">
        <p id="b_minutes">0</p><p class="semicolon">:</p><p id="b_seconds">10</p>
    </div>
    <p id="points" class="timer">0</p>
    <button id="start" type="button" class="btn btn-primary">Start</button>
    <button id="stop" type="button" class="btn btn-primary">Pause</button>
    <button id="reset" type="button" class="btn btn-primary">Reset</button>
    @*<button id="bank" type="button" class="btn btn-primary">Complete</button>*@


    @*@Html.ActionLink("Complete", "Index", "Reward", new { area = "" }, new { @class = "btn btn-primary", @id = "bank" })*@
</div>



@*<div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@